spring:
  application:
    name: "eurekaserver"
# Configuracion de conexion al configserver    
  config:
    import: "optional:configserver:http://localhost:8071/"
# Configuracion de actuator
management:
  endpoints:
    web:
      exposure:
        include:
        - health
        - metrics
        - prometheus
## Agregar una etiqueta (tag) personalizada a todas las métricas que genera Actuator en micrometer llamado application como valor el nombre del microservicio
  metrics:
    tags:
      application: ${spring.application.name}
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
#Estableciendo la configuracion de logging DEBUG en el paquete com.eazybites.eurekaserver del proyecto
logging:
  level:
    com:
      eazybites:
        eurekaserver: DEBUG
# Estableciendo un patron de log personalizado para el microservicio
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"            
